version: '2'

services:
  peer-base:
    image: hyperledger/fabric-peer:2.2
    environment:
      - TZ=Asia/Taipei
      # - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same bridge network as the peers
      # https://docs.docker.com/compose/networking/
      # - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_${NETWORK_NAME}
      - FABRIC_LOGGING_SPEC=INFO
      # enabled TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # gossip @_@!!! leader採自動選舉，不採指定方式
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "6"
